#!/usr/bin/env python3
"""
compare_runs.py  --  before/after comparison of two ns-O-RAN runs.

Usage:
    python3 compare_runs.py                 # uses the built-in baseline vs -3dB pair
    python3 compare_runs.py BASE_UUID NEW_UUID [--label-a NAME] [--label-b NAME]
    python3 compare_runs.py ... --html out.html   # also write a styled HTML card

Prints a clean before/after/delta/percent table. Reuses analysis/load_metric.py,
so the numbers match every other analysis in the project.
"""
import sys, os, argparse, io, contextlib

sys.path.insert(0, 'analysis')
import load_metric as lm

# Chosen (documented) weights — passed explicitly because the module default is the old set.
WEIGHTS = {'prb': 0.15, 'ues': 0.40, 'vol': 0.10, 'qual': 0.35}
lm.TOTAL_UES = 35

DEFAULT_A = '44dadaab-51d6-4eea-90cb-b6fcf53a040b'   # baseline, 35 UE
DEFAULT_B = '5e89652b-3c20-4b29-bf4f-bba31fba96b2'   # -3 dB on cell 8


def metrics_for(uuid):
    """Return the headline metrics for one run, silencing the module's diagnostics."""
    path = f'output/{uuid}/database.db'
    if not os.path.exists(path):
        sys.exit(f"ERROR: database not found: {path}")
    # load_metric prints diagnostics to stdout; capture and discard them
    with contextlib.redirect_stdout(io.StringIO()):
        v = lm.build_load_view(path)
        d = lm.compute_load(v, weights=WEIGHTS)
    return {
        'Data delivered (MB)':  (d['vol_bytes'].sum() / 1e6,    True),
        'Total backlog (MB)':   (d['buffer_bytes'].sum() / 1e6, False),
        'Signal-loss events':   (int((v['sinr_min'] == float('-inf')).sum()), False),
    }


def pct(base, new):
    if base == 0:
        return "n/a" if new == 0 else "new"
    return f"{(new - base) / base * 100:+.1f}%"


def verdict(base, new, higher_is_better):
    if new == base:
        return "no change"
    better = (new > base) if higher_is_better else (new < base)
    return "IMPROVED" if better else "worse"


def fmt(x):
    return f"{x:,.1f}" if isinstance(x, float) else f"{x:,}"


def print_table(a, b, la, lb):
    name_w = max(len(k) for k in a) + 2
    total_w = name_w + 13 + 13 + 11 + 12
    print()
    print("=" * total_w)
    print(f"{'Metric':<{name_w}}{la:>13}{lb:>13}{'Change':>11}{'Result':>12}")
    print("-" * total_w)
    for k in a:
        base, hib = a[k]
        new, _ = b[k]
        print(f"{k:<{name_w}}{fmt(base):>13}{fmt(new):>13}{pct(base,new):>11}{verdict(base,new,hib):>12}")
    print("=" * total_w)
    print()


HTML_TMPL = """<!doctype html><html><head><meta charset="utf-8">
<title>Run comparison</title>
<style>
 body{{font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;background:#f5f7fa;padding:40px;color:#1a2b3c}}
 .card{{max-width:760px;margin:auto;background:#fff;border-radius:16px;box-shadow:0 4px 24px rgba(0,0,0,.08);overflow:hidden}}
 .head{{background:#1F4E79;color:#fff;padding:22px 30px}}
 .head h1{{margin:0;font-size:20px}} .head p{{margin:6px 0 0;opacity:.85;font-size:14px}}
 table{{width:100%;border-collapse:collapse}}
 th,td{{padding:16px 30px;text-align:right}} th:first-child,td:first-child{{text-align:left}}
 thead th{{background:#eef2f7;font-size:13px;text-transform:uppercase;letter-spacing:.03em;color:#556}}
 tbody tr{{border-top:1px solid #eef1f4}}
 .metric{{font-weight:600}}
 .delta{{font-weight:700}}
 .up{{color:#2E7D32}} .down{{color:#C00000}}
 .pill{{display:inline-block;padding:3px 12px;border-radius:20px;font-size:12px;font-weight:700}}
 .pill.good{{background:#E3F0E4;color:#2E7D32}} .pill.bad{{background:#FBE4E4;color:#C00000}}
 .foot{{padding:16px 30px;font-size:12px;color:#889;background:#fafbfc}}
</style></head><body><div class="card">
<div class="head"><h1>Network comparison &mdash; {la} vs {lb}</h1>
<p>35 users &middot; one &minus;3 dB offset on the saturated cell &middot; figures from recorded simulator output</p></div>
<table><thead><tr><th>Metric</th><th>{la}</th><th>{lb}</th><th>Change</th><th></th></tr></thead>
<tbody>{rows}</tbody></table>
<div class="foot">Generated by compare_runs.py using analysis/load_metric.py &middot; weights 0.15/0.40/0.10/0.35</div>
</div></body></html>"""


def write_html(a, b, la, lb, path):
    rows = ""
    for k in a:
        base, hib = a[k]
        new, _ = b[k]
        p = pct(base, new)
        good = verdict(base, new, hib) == "IMPROVED"
        cls = "good" if good else ("bad" if verdict(base,new,hib)=="worse" else "")
        label = "improved" if good else ("worse" if cls=="bad" else "no change")
        dcls = "up" if good else ("down" if cls=="bad" else "")
        rows += (f"<tr><td class='metric'>{k}</td><td>{fmt(base)}</td><td>{fmt(new)}</td>"
                 f"<td class='delta {dcls}'>{p}</td>"
                 f"<td><span class='pill {cls}'>{label}</span></td></tr>")
    html = HTML_TMPL.format(la=la, lb=lb, rows=rows)
    with open(path, "w") as f:
        f.write(html)
    print(f"HTML written to {path}  (open it in a browser)")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("base", nargs="?", default=DEFAULT_A)
    ap.add_argument("new",  nargs="?", default=DEFAULT_B)
    ap.add_argument("--label-a", default="Do nothing")
    ap.add_argument("--label-b", default="-3 dB cell 8")
    ap.add_argument("--html", default=None)
    args = ap.parse_args()

    a = metrics_for(args.base)
    b = metrics_for(args.new)
    print_table(a, b, args.label_a, args.label_b)
    if args.html:
        write_html(a, b, args.label_a, args.label_b, args.html)


if __name__ == "__main__":
    main()
