[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ns_o_ran_gym"
version = "0.1.0"
description = "O-RAN MARL Gymnasium environment for ns-3 mmWave"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pyzmq",
    "numpy",
    "gymnasium"
]

# Tell setuptools: "When someone imports 'ns_o_ran_gym', look in the current directory (.)"
[tool.setuptools]
package-dir = {"ns_o_ran_gym" = "."}